# Generated by Django 4.2.1 on 2023-05-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_dayhabit_day_habits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayhabit',
            old_name='checked',
            new_name='completed',
        ),
    ]
