version: '3'
services:
  postgres:
    image: postgres:15.0-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: habit-tracker
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - postgres
    ports:
      - "5432:5432"

  api:
    build:
      context: .
    volumes:
      - ./backend:/backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - postgres
    command: >
      sh -c "python manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

networks:
  postgres: