# Generated by Django 4.2.1 on 2023-05-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_create_model_habit'),
        ('days', '0003_dayhabit_day_habits'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dayhabit',
            unique_together={('habit', 'day')},
        ),
    ]
